[phases.setup]
nixPkgs = ["jdk21", "maven"]
aptPkgs = []

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/recipe-platform-1.0.0.jar"
